#!/bin/bash
# Author: Marc Garcia-Garcera
#  usage: memused [program arg1 arg2 ...]

"$@" &
pid=$!
status=$(ps -o rss -o vsz -o pid | grep $pid)
max=0
while [ "${#status}" -gt "0" ];
do
    sleep 0.1
    mem=$(ps -o rss -o vsz -o pid | grep $pid | awk '{print $1}')
    mem=$((mem/1024))
    if [ "0$mem" -gt "0$max" ] 2>/dev/null; then
        max=$mem
    fi
status=$(ps -o rss -o vsz -o pid | grep $pid)
done
wait $pid
ret=$?

echo "maximal memory used: $max MB"

exit $ret
